### ISSUE TITLE
Add Twitch Whisper Support

### ISSUE THREAD

**Issue by pinghajen** [EveryGoodWork/ChapterVerse#36]
Add support for !joinchannel in whispers. This could be extended to all commands if desired.

**Comment by PeterMHammond** [comment]
Support to receive all commands via whispers to the bot account has been implemented, HOWEVER, whispers from bots are heavily restricted to reduce on the spam issues.
https://discuss.dev.twitch.com/t/bot-help-whispers/25729/7
So although the command is received and executed, it is likely that the reply will fail in response.
Meaning !joinchannel will work, however there will be no response to the user to indicate the command was successful.
They can test it's success by trying commands on their channel's chat.

**Comment by PeterMHammond** [comment]
The whisper will be echo'd to the account's chat that ChapterVerse is running as.
![image](https://github.com/EveryGoodWork/ChapterVerse/assets/74989099/ffbe0e90-a24c-4af9-a24e-ce99f0dcbf22)
