### ISSUE TITLE
Include available translations in !translation help response

### ISSUE THREAD

**Issue by pinghajen** [EveryGoodWork/ChapterVerse#52]
The list of available translations should be included in the help response, might also be useful to make the list dynamic if it's not already.

**Comment by PeterMHammond** [comment]
The list of available translations are available from the main !help and this does show a dynamic list of Available translations.  Adding it to the !Translation Help is a great idea, and should be pretty direct if copied from the !help function.  Feel free to submit a PR for this.

**Comment by PeterMHammond** [comment]
The list of available translations are available from the main !help and this does show a dynamic list of Available translations. Adding it to the !Translation Help is a great idea, and should be pretty direct if copied from the !help function. Feel free to submit a PR for this.
